# name: TelegramBot

# on:
#   pull_request:
#     branches: [ devel ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@master
#       - name: send custom message with args
#         uses: appleboy/telegram-action@master
#         with:
#           to: "-groupid"
#           token: "token here"
#           args: ğŸ‘¨ğŸ»â€ğŸ’» UsuÃ¡rio ${{github.actor}}, fez um ${{ github.event_name }}. no repositÃ³rio ${{ github.repository }} | FunÃ§Ã£o ${{github.job}}.
