# name: TelegramBot

# on:
#   push:
#     branches: [ main, devel ]

# jobs:
#   Merge:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@master
#       - name: send custom message with args
#         uses: appleboy/telegram-action@master
#         with:
#           to: "-groupid"
#           token: "token here"
#           args: ğŸ‘¨ğŸ»â€ğŸ’» UsuÃ¡rio ${{github.actor}}, fez um MERGE no repositÃ³rio ${{ github.repository }} | Atualizar sua branch!!!.
